### ISSUE TITLE
Supongo que debería ser privado el método.

### ISSUE THREAD

**Issue by maurociancio** [tflopezhidalgo/seminario#15]
https://github.com/tflopezhidalgo/seminario/blob/a8affe4a4cf86a00447df1110086ee2d65e90dcb/grails-app/domain/previapp/Bebida.groovy#L25

**Comment by tflopezhidalgo** [comment]
Pasé todos los métodos de validación a privados: 

https://github.com/tflopezhidalgo/seminario/commit/e7000b6f8e8356c4d49928952955968012edcf80
