### ISSUE TITLE
La lista no puede ser vacía? Y dividís por cero?

### ISSUE THREAD

**Issue by maurociancio** [tflopezhidalgo/seminario#17]
https://github.com/tflopezhidalgo/seminario/blob/a8affe4a4cf86a00447df1110086ee2d65e90dcb/grails-app/domain/previapp/Lugar.groovy#L78

**Comment by tflopezhidalgo** [comment]
Corregido en:

https://github.com/tflopezhidalgo/seminario/commit/0dc5af35f96b1fd96dbab1524f1c4ee03ae8f462
