### ISSUE TITLE
Idem división por cero?

### ISSUE THREAD

**Issue by maurociancio** [tflopezhidalgo/seminario#18]
https://github.com/tflopezhidalgo/seminario/blob/a8affe4a4cf86a00447df1110086ee2d65e90dcb/grails-app/domain/previapp/Lugar.groovy#L88

**Comment by tflopezhidalgo** [comment]
Corregido en:

https://github.com/tflopezhidalgo/seminario/commit/0dc5af35f96b1fd96dbab1524f1c4ee03ae8f462
