### ISSUE TITLE
métodos privados?

### ISSUE THREAD

**Issue by maurociancio** [tflopezhidalgo/seminario#19]
https://github.com/tflopezhidalgo/seminario/blob/a8affe4a4cf86a00447df1110086ee2d65e90dcb/grails-app/domain/previapp/Lugar.groovy#L45

**Comment by tflopezhidalgo** [comment]
Pasé todos los métodos de validación a privados: 

https://github.com/tflopezhidalgo/seminario/commit/e7000b6f8e8356c4d49928952955968012edcf80
