### ISSUE TITLE
Xq no validar esto en el constructor?

### ISSUE THREAD

**Issue by maurociancio** [tflopezhidalgo/seminario#22]
https://github.com/tflopezhidalgo/seminario/blob/a8affe4a4cf86a00447df1110086ee2d65e90dcb/grails-app/domain/previapp/Visita.groovy#L14

**Comment by tflopezhidalgo** [comment]
Esto ya había sido modificado. El código lo valida en `validarFecha` ahora

https://github.com/tflopezhidalgo/seminario/blob/master/grails-app/domain/previapp/Visita.groovy#L34
