### ISSUE TITLE
return es opcional

### ISSUE THREAD

**Issue by maurociancio** [tflopezhidalgo/seminario#23]
https://github.com/tflopezhidalgo/seminario/blob/a8affe4a4cf86a00447df1110086ee2d65e90dcb/grails-app/domain/previapp/Visita.groovy#L54

**Comment by tflopezhidalgo** [comment]
Corregido en https://github.com/tflopezhidalgo/seminario/commit/2cbcf384695648cec563fc42cbdaaea20e5cf3d8
