### ISSUE TITLE
Los mensajes de las excepciones no son mensajes para los usuarios

### ISSUE THREAD

**Issue by maurociancio** [tflopezhidalgo/seminario#24]
https://github.com/tflopezhidalgo/seminario/blob/a8affe4a4cf86a00447df1110086ee2d65e90dcb/grails-app/controllers/previapp/LugarController.groovy#L122

No soportan i18n y probablemente tengan info que el usuario no deba ver.

**Comment by tflopezhidalgo** [comment]
Entiendo que hacer el  `getMessage()` está mal. Validar como el resto está correcto? Es decir:

```groovy
...
 } catch(CapacidadMaximaInvalidaError e) {
    def msg = "${e.capacidadInvalida} no es un valor válido para la capacidad"
    redirect(action: 'create', params: [errorMsg: msg])
...
```

**Comment by maurociancio** [comment]
va bien!
