### ISSUE TITLE
Mucha lógica en el controlador

### ISSUE THREAD

**Issue by maurociancio** [tflopezhidalgo/seminario#25]
https://github.com/tflopezhidalgo/seminario/blob/a8affe4a4cf86a00447df1110086ee2d65e90dcb/grails-app/controllers/previapp/VisitaController.groovy#L45

No se puede pasar todo eso a un servicio?

**Comment by tflopezhidalgo** [comment]
Sí, había olvidado subir esta parte. Lo había pasado hace un tiempo:

https://github.com/tflopezhidalgo/seminario/commit/8425a96063542fd718822ba5e7103272b36ba9d0#diff-e65c8cf074d0add6bd40181b5bc66fa3251a0c7cb318592e18731f61ec596db6R22

Quedó finalmente en `VisitaService`
