### ISSUE TITLE
El método puede ser:

### ISSUE THREAD

**Issue by maurociancio** [tflopezhidalgo/seminario#28]
https://github.com/tflopezhidalgo/seminario/blob/a8affe4a4cf86a00447df1110086ee2d65e90dcb/grails-app/services/previapp/VisitaService.groovy#L34

Visita.findByUsuarioAndLugar(usuario, lugar)
así de una.
se convierte a false si es null y true si no es null

**Comment by tflopezhidalgo** [comment]
Corregido en: https://github.com/tflopezhidalgo/seminario/commit/2cbcf384695648cec563fc42cbdaaea20e5cf3d8#diff-e65c8cf074d0add6bd40181b5bc66fa3251a0c7cb318592e18731f61ec596db6R50
