### ISSUE TITLE
10 que?

### ISSUE THREAD

**Issue by maurociancio** [tflopezhidalgo/seminario#29]
https://github.com/tflopezhidalgo/seminario/blob/a8affe4a4cf86a00447df1110086ee2d65e90dcb/grails-app/services/previapp/ZonaService.groovy#L28

que son esos 10?
metros? kms? millas nauticas :P?

**Comment by tflopezhidalgo** [comment]
Agregué la clase kilómetro para manejar estos casos.

https://github.com/tflopezhidalgo/seminario/commit/8425a96063542fd718822ba5e7103272b36ba9d0#diff-fdb68f211a87694cb3f26b38483a244940d15fe8d31453472c53410892a2ec9eR9

Se busca entonces para cada zona en un radio de 10km a la redonda (simulando la distribución geográfica con el método random de math)
